### ISSUE TITLE
按照惯例先给star再提问

### ISSUE THREAD

**Issue by codeplay2024** [MiHaKun/Telegram-interactive-bot#1]
米哈大佬，我在部署你的机器人之后遇到一个问题：比如我在后台删掉和某用户的聊天窗口（话题）之后，这个用户就再也不能使用机器人发起新的话题（对话）了。
![image](https://github.com/MiHaKun/Telegram-interactive-bot/assets/166860092/e5f2a7d6-373d-4e34-a725-9c421c34eda2)
机器人返回错误消息给用户：
```
发送失败: Message thread not found
```

**Comment by MiHaKun** [comment]
当时的版本就是如此。本质删除就让这个客户的消息无所归属。可以屏蔽掉骚扰。

新版本这方面会加强。

**Comment by MiHaKun** [comment]
近期更新。所以，先关闭了。
